version: 2
plugins:
  fixme:
    enabled: true
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
exclude_patterns:
  - "apidocs/**/*"
  - "docs/**/*"