version: 2
jobs:
  build:
    branches:
      ignore: gh-pages
    docker:
      - image: 'circleci/node:9.4.0'
      - image: 'circleci/mongo:3.6.2'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install && npm install greenkeeper-lockfile@1
      - run:
          name: List dependencies
          command: npm list
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Linter code
          command: npm run lint
      - run:
          name: Save change
          command: |
            git config user.email "tedxku2018.bot@gmail.com"
            git config user.name "TEDxKU2018"
            git status
            git commit -am "Update"
      - run:
          name: Testing application
          command: |
            ./node_modules/.bin/greenkeeper-lockfile-update &&
            npm run ci:test &&
            ./node_modules/.bin/greenkeeper-lockfile-upload
          environment:
            MOCHA_FILE: test/results/test-results.xml
      - run:
          name: Create report
          command: 'npm run ci:report'
      - store_test_results:
          path: test/results
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: npm/logs
